[package]
name = "yunq-infra-postgres"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
yunq-ast = { workspace = true }
yunq-rules-engine = { workspace = true }
sqlx = { workspace = true }
tokio = { workspace = true }
thiserror = { workspace = true }
serde_json = { workspace = true }
serde = { workspace = true }
chrono = { version = "0.4", features = ["serde"] }
sha2 = { workspace = true }
flate2 = { workspace = true }
async-trait = "0.1"
aes-gcm = { workspace = true }
base64 = { workspace = true }
