[package]
name = "yunq-symbols"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true
description = "Symbol resolution for yunq's cross-file analysis"
repository.workspace = true
homepage.workspace = true
keywords.workspace = true
categories.workspace = true

[dependencies]
yunq-ast = { workspace = true }

[dev-dependencies]
yunq-rules-engine = { workspace = true }
yunq-parser-typescript = { workspace = true }
yunq-parser-rust = { workspace = true }
yunq-parser-python = { workspace = true }
