[package]
name = "yunq-rules-smells"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
yunq-ast = { workspace = true }
yunq-rules-engine = { workspace = true }

[dev-dependencies]
yunq-parser-rust = { workspace = true }
yunq-parser-typescript = { workspace = true }
