[package]
name = "vord-infra-gitlab"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true
description = "GitLab adapter for vord"
repository.workspace = true
homepage.workspace = true
keywords.workspace = true
categories.workspace = true

[dependencies]
vord-rules-engine = { workspace = true }
reqwest = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
