[package]
name = "yunq-parser-yaml"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
yunq-ast = { workspace = true }
yunq-rules-engine = { workspace = true }
yunq-cpd = { workspace = true }
yunq-treesitter-tokens = { workspace = true }
tree-sitter = { workspace = true }
tree-sitter-yaml = "0.7.2"
