import {
  Project,
  Issue,
  QualityGate,
  QualityProfile,
  RuleDefinition,
  FileNode,
  SystemInfo,
  MetricDefinition
} from '../types';

export const MOCK_PROJECTS: Project[] = [
  {
    key: 'org.sonarqube:sonar-core',
    name: 'sonar-core-engine',
    description: 'Main SonarQube core analysis server and web app engine.',
    qualityGateStatus: 'PASSED',
    lastAnalysisDate: '2026-07-21T14:32:00Z',
    language: 'TypeScript',
    tags: ['core', 'backend', 'api'],
    visibility: 'public',
    metrics: {
      bugs: 0,
      bugsRating: 'A',
      vulnerabilities: 0,
      vulnerabilitiesRating: 'A',
      securityHotspots: 2,
      securityHotspotsReviewed: 100,
      codeSmells: 14,
      codeSmellsRating: 'A',
      debtMinutes: 140, // 2h 20m
      coverage: 88.5,
      uncoveredLines: 124,
      duplications: 1.2,
      duplicatedBlocks: 3,
      ncloc: 42850,
      newBugs: 0,
      newVulnerabilities: 0,
      newCodeSmells: 2,
      newCoverage: 92.4,
      newDuplications: 0.0,
    },
    branches: [
      { name: 'main', isMain: true, status: 'PASSED', lastAnalysis: '2h ago' },
      { name: 'develop', isMain: false, status: 'PASSED', lastAnalysis: '4h ago' },
      { name: 'feature/auth-oidc', isMain: false, status: 'WARN', lastAnalysis: '1d ago' },
    ],
    sparkline: [
      { date: 'Jun 21', bugs: 2, codeSmells: 28, coverage: 82.1 },
      { date: 'Jun 28', bugs: 1, codeSmells: 22, coverage: 84.0 },
      { date: 'Jul 05', bugs: 1, codeSmells: 19, coverage: 85.5 },
      { date: 'Jul 12', bugs: 0, codeSmells: 16, coverage: 87.2 },
      { date: 'Jul 19', bugs: 0, codeSmells: 14, coverage: 88.5 },
    ],
  },
  {
    key: 'com.acme:payment-gateway-service',
    name: 'payment-gateway-service',
    description: 'PCI-DSS Compliant microservice for credit card processing and PayPal integration.',
    qualityGateStatus: 'FAILED',
    failedGateConditions: [
      'Coverage on New Code is 64.2% (required >= 80.0%)',
      '1 Critical Security Vulnerability found on New Code'
    ],
    lastAnalysisDate: '2026-07-21T11:15:00Z',
    language: 'Java',
    tags: ['payments', 'pci', 'finance', 'microservice'],
    visibility: 'private',
    metrics: {
      bugs: 5,
      bugsRating: 'C',
      vulnerabilities: 3,
      vulnerabilitiesRating: 'D',
      securityHotspots: 8,
      securityHotspotsReviewed: 37.5,
      codeSmells: 87,
      codeSmellsRating: 'B',
      debtMinutes: 1840, // 3d 6h
      coverage: 64.2,
      uncoveredLines: 1280,
      duplications: 4.8,
      duplicatedBlocks: 21,
      ncloc: 28400,
      newBugs: 2,
      newVulnerabilities: 1,
      newCodeSmells: 12,
      newCoverage: 58.1,
      newDuplications: 2.1,
    },
    branches: [
      { name: 'main', isMain: true, status: 'FAILED', lastAnalysis: '5h ago' },
      { name: 'release/v2.4', isMain: false, status: 'PASSED', lastAnalysis: '2d ago' },
      { name: 'fix/stripe-webhook', isMain: false, status: 'PASSED', lastAnalysis: '12h ago' },
    ],
    sparkline: [
      { date: 'Jun 21', bugs: 1, codeSmells: 45, coverage: 71.0 },
      { date: 'Jun 28', bugs: 2, codeSmells: 52, coverage: 69.5 },
      { date: 'Jul 05', bugs: 3, codeSmells: 68, coverage: 67.2 },
      { date: 'Jul 12', bugs: 4, codeSmells: 79, coverage: 65.0 },
      { date: 'Jul 19', bugs: 5, codeSmells: 87, coverage: 64.2 },
    ],
  },
  {
    key: 'io.enterprise:identity-auth-api',
    name: 'identity-auth-api',
    description: 'OAuth2 / OpenID Connect authorization server with MFA support.',
    qualityGateStatus: 'PASSED',
    lastAnalysisDate: '2026-07-20T18:45:00Z',
    language: 'Go',
    tags: ['auth', 'security', 'oauth2'],
    visibility: 'private',
    metrics: {
      bugs: 0,
      bugsRating: 'A',
      vulnerabilities: 0,
      vulnerabilitiesRating: 'A',
      securityHotspots: 1,
      securityHotspotsReviewed: 100,
      codeSmells: 8,
      codeSmellsRating: 'A',
      debtMinutes: 80,
      coverage: 94.1,
      uncoveredLines: 42,
      duplications: 0.4,
      duplicatedBlocks: 1,
      ncloc: 15200,
      newBugs: 0,
      newVulnerabilities: 0,
      newCodeSmells: 0,
      newCoverage: 96.0,
      newDuplications: 0.0,
    },
    branches: [
      { name: 'main', isMain: true, status: 'PASSED', lastAnalysis: '1d ago' },
    ],
    sparkline: [
      { date: 'Jun 21', bugs: 0, codeSmells: 12, coverage: 91.0 },
      { date: 'Jun 28', bugs: 0, codeSmells: 10, coverage: 92.5 },
      { date: 'Jul 05', bugs: 0, codeSmells: 9, coverage: 93.8 },
      { date: 'Jul 12', bugs: 0, codeSmells: 8, coverage: 94.1 },
      { date: 'Jul 19', bugs: 0, codeSmells: 8, coverage: 94.1 },
    ],
  },
  {
    key: 'com.analytics:data-pipeline-py',
    name: 'data-pipeline-processor',
    description: 'PySpark ETL processor for large scale data warehouse ingestion.',
    qualityGateStatus: 'PASSED',
    lastAnalysisDate: '2026-07-21T08:10:00Z',
    language: 'Python',
    tags: ['data', 'etl', 'python', 'spark'],
    visibility: 'public',
    metrics: {
      bugs: 1,
      bugsRating: 'B',
      vulnerabilities: 0,
      vulnerabilitiesRating: 'A',
      securityHotspots: 4,
      securityHotspotsReviewed: 75.0,
      codeSmells: 34,
      codeSmellsRating: 'A',
      debtMinutes: 320,
      coverage: 81.3,
      uncoveredLines: 310,
      duplications: 1.8,
      duplicatedBlocks: 4,
      ncloc: 19800,
      newBugs: 0,
      newVulnerabilities: 0,
      newCodeSmells: 3,
      newCoverage: 85.0,
      newDuplications: 0.5,
    },
    branches: [
      { name: 'main', isMain: true, status: 'PASSED', lastAnalysis: '8h ago' },
    ],
    sparkline: [
      { date: 'Jun 21', bugs: 3, codeSmells: 50, coverage: 78.0 },
      { date: 'Jun 28', bugs: 2, codeSmells: 42, coverage: 79.5 },
      { date: 'Jul 05', bugs: 1, codeSmells: 38, coverage: 80.8 },
      { date: 'Jul 12', bugs: 1, codeSmells: 35, coverage: 81.0 },
      { date: 'Jul 19', bugs: 1, codeSmells: 34, coverage: 81.3 },
    ],
  },
  {
    key: 'com.frontend:storefront-nextjs',
    name: 'storefront-ecommerce-ui',
    description: 'Customer facing e-commerce web application built with React and Tailwind.',
    qualityGateStatus: 'FAILED',
    failedGateConditions: [
      'Duplicated Lines on New Code is 6.5% (required <= 3.0%)'
    ],
    lastAnalysisDate: '2026-07-21T15:00:00Z',
    language: 'TypeScript',
    tags: ['frontend', 'react', 'ecommerce'],
    visibility: 'public',
    metrics: {
      bugs: 2,
      bugsRating: 'B',
      vulnerabilities: 1,
      vulnerabilitiesRating: 'B',
      securityHotspots: 5,
      securityHotspotsReviewed: 60.0,
      codeSmells: 112,
      codeSmellsRating: 'C',
      debtMinutes: 2420,
      coverage: 72.8,
      uncoveredLines: 840,
      duplications: 6.5,
      duplicatedBlocks: 18,
      ncloc: 34100,
      newBugs: 1,
      newVulnerabilities: 0,
      newCodeSmells: 18,
      newCoverage: 70.1,
      newDuplications: 6.5,
    },
    branches: [
      { name: 'main', isMain: true, status: 'FAILED', lastAnalysis: '1h ago' },
    ],
    sparkline: [
      { date: 'Jun 21', bugs: 1, codeSmells: 80, coverage: 75.0 },
      { date: 'Jun 28', bugs: 1, codeSmells: 92, coverage: 74.2 },
      { date: 'Jul 05', bugs: 2, codeSmells: 104, coverage: 73.5 },
      { date: 'Jul 12', bugs: 2, codeSmells: 108, coverage: 73.0 },
      { date: 'Jul 19', bugs: 2, codeSmells: 112, coverage: 72.8 },
    ],
  }
];

export const MOCK_ISSUES: Issue[] = [
  {
    id: 'ISSUE-1001',
    key: 'AWx908234-JAVA-SQL',
    ruleKey: 'java:S2077',
    ruleName: 'SQL queries should be constructed using parameterized queries',
    severity: 'CRITICAL',
    type: 'VULNERABILITY',
    status: 'OPEN',
    message: 'Constructing SQL queries by concatenating user-controlled strings can lead to SQL Injection attacks.',
    projectKey: 'com.acme:payment-gateway-service',
    projectName: 'payment-gateway-service',
    component: 'src/main/java/com/acme/payment/repository/PaymentDAO.java',
    line: 42,
    effortMinutes: 30,
    assignee: 'Alex Mercer',
    author: 'j.smith@acme.com',
    creationDate: '2026-07-21T10:12:00Z',
    updateDate: '2026-07-21T10:12:00Z',
    tags: ['sql-injection', 'cwe-89', 'security', 'owasp-a1'],
    cleanCodeAttribute: 'Security-Sensitive Data Sanitization',
    codeSnippet: [
      { line: 38, code: '    public List<Transaction> findByAccountAndType(String accountId, String type) {' },
      { line: 39, code: '        Connection conn = dbPool.getConnection();' },
      { line: 40, code: '        Statement stmt = conn.createStatement();' },
      { line: 41, code: '        // Unsanitized raw dynamic query assembly' },
      { line: 42, code: '        String sql = "SELECT * FROM transactions WHERE account_id = \'" + accountId + "\' AND type = \'" + type + "\'";', issueId: 'ISSUE-1001', issueSeverity: 'CRITICAL', issueMessage: 'SQL Injection Risk: accountId concatenated directly' },
      { line: 43, code: '        ResultSet rs = stmt.executeQuery(sql);' },
      { line: 44, code: '        return parseTransactions(rs);' },
      { line: 45, code: '    }' },
    ],
    dataFlowTrace: [
      { step: 1, file: 'PaymentController.java', line: 18, code: 'String accountId = request.getParameter("acc");', description: 'User input originates from HTTP request parameter "acc"' },
      { step: 2, file: 'PaymentService.java', line: 29, code: 'return paymentDAO.findByAccountAndType(accountId, type);', description: 'Parameter passed into DAO without validation or escaping' },
      { step: 3, file: 'PaymentDAO.java', line: 42, code: 'String sql = "SELECT * FROM transactions WHERE account_id = \'" + accountId + "\'...";', description: 'Concatenated into SQL query string executed on database' }
    ],
    ruleDescription: {
      why: 'Dynamic execution of SQL statements with string concatenation exposes application to SQL Injection vulnerabilities, allowing malicious actors to manipulate query logic, bypass authentication, or extract sensitive data.',
      howToFix: 'Use prepared statements (PreparedStatement) with bind parameters or an object-relational mapping (ORM) framework like Hibernate/JPA.',
      nonCompliant: 'String sql = "SELECT * FROM users WHERE name = \'" + userName + "\'";\nStatement stmt = connection.createStatement();\nResultSet rs = stmt.executeQuery(sql);',
      compliant: 'String sql = "SELECT * FROM users WHERE name = ?";\nPreparedStatement pstmt = connection.prepareStatement(sql);\npstmt.setString(1, userName);\nResultSet rs = pstmt.executeQuery();'
    }
  },
  {
    id: 'ISSUE-1002',
    key: 'AWx908235-TS-NULL',
    ruleKey: 'typescript:S2259',
    ruleName: 'Null pointers should not be dereferenced',
    severity: 'MAJOR',
    type: 'BUG',
    status: 'OPEN',
    message: 'TypeError risk: "user" can be undefined here when fetching session fails.',
    projectKey: 'org.sonarqube:sonar-core',
    projectName: 'sonar-core-engine',
    component: 'src/features/auth/useSession.ts',
    line: 28,
    effortMinutes: 15,
    assignee: 'Sarah Connor',
    author: 's.connor@sonarqube.org',
    creationDate: '2026-07-21T12:00:00Z',
    updateDate: '2026-07-21T12:00:00Z',
    tags: ['null-pointer', 'type-safety'],
    codeSnippet: [
      { line: 25, code: 'export function getUserDisplayName(sessionResponse: SessionResponse | null): string {' },
      { line: 26, code: '  const user = sessionResponse.data?.user;' },
      { line: 27, code: '  // Missing check for user existence before accessing profile property' },
      { line: 28, code: '  return user.profile.firstName + " " + user.profile.lastName;', issueId: 'ISSUE-1002', issueSeverity: 'MAJOR', issueMessage: 'Object is possibly "undefined"' },
      { line: 29, code: '}' },
    ],
    ruleDescription: {
      why: 'Accessing properties on null or undefined objects throws runtime TypeErrors, causing application crashes or unhandled promise rejections.',
      howToFix: 'Use optional chaining (`user?.profile?.firstName`) or explicit null-checks.',
      nonCompliant: 'return user.profile.firstName;',
      compliant: 'return user?.profile?.firstName ?? "Anonymous";'
    }
  },
  {
    id: 'ISSUE-1003',
    key: 'AWx908236-GO-RACE',
    ruleKey: 'go:S2699',
    ruleName: 'Goroutines should synchronize access to shared memory',
    severity: 'BLOCKER',
    type: 'BUG',
    status: 'CONFIRMED',
    message: 'Concurrent map writes detected without sync.Mutex guard.',
    projectKey: 'io.enterprise:identity-auth-api',
    projectName: 'identity-auth-api',
    component: 'pkg/auth/token_cache.go',
    line: 55,
    effortMinutes: 45,
    assignee: 'David Miller',
    author: 'd.miller@enterprise.io',
    creationDate: '2026-07-20T14:20:00Z',
    updateDate: '2026-07-21T09:00:00Z',
    tags: ['concurrency', 'race-condition', 'go-routine'],
    codeSnippet: [
      { line: 52, code: 'func (c *TokenCache) Set(key string, token *Token) {' },
      { line: 53, code: '    go func() {' },
      { line: 54, code: '        // Concurrent write to non-thread-safe map' },
      { line: 55, code: '        c.tokens[key] = token', issueId: 'ISSUE-1003', issueSeverity: 'BLOCKER', issueMessage: 'Data race: map write without mutex lock' },
      { line: 56, code: '    }()' },
      { line: 57, code: '}' },
    ],
    ruleDescription: {
      why: 'Go maps are not safe for concurrent usage. Writing to a map concurrently from multiple goroutines panics the Go runtime with a fatal data race.',
      howToFix: 'Protect map access with a `sync.RWMutex` or use `sync.Map`.',
      nonCompliant: 'c.tokens[key] = token',
      compliant: 'c.mu.Lock()\ndefer c.mu.Unlock()\nc.tokens[key] = token'
    }
  },
  {
    id: 'ISSUE-1004',
    key: 'AWx908237-PY-SECRET',
    ruleKey: 'python:S1812',
    ruleName: 'Hardcoded credentials should not be stored in source code',
    severity: 'CRITICAL',
    type: 'VULNERABILITY',
    status: 'OPEN',
    message: 'AWS Access Key string literal detected in ETL credentials configuration module.',
    projectKey: 'com.analytics:data-pipeline-py',
    projectName: 'data-pipeline-processor',
    component: 'etl/config/aws_client.py',
    line: 14,
    effortMinutes: 10,
    assignee: 'Elena Rostova',
    author: 'e.rostova@analytics.com',
    creationDate: '2026-07-19T11:40:00Z',
    updateDate: '2026-07-19T11:40:00Z',
    tags: ['hardcoded-secret', 'credentials', 'aws', 'cwe-798'],
    codeSnippet: [
      { line: 12, code: '# AWS S3 Bucket Client Initialization' },
      { line: 13, code: 'AWS_REGION = "us-east-1"' },
      { line: 14, code: 'AWS_SECRET_KEY = "AKIAIOSFODNN7EXAMPLE"', issueId: 'ISSUE-1004', issueSeverity: 'CRITICAL', issueMessage: 'Hardcoded AWS credential detected' },
      { line: 15, code: 's3_client = boto3.client("s3", aws_secret_access_key=AWS_SECRET_KEY)' },
    ],
    ruleDescription: {
      why: 'Committing credentials, passwords, or API keys directly into source code control exposes infrastructure to leaks, unauthorized access, and automated scanner credential harvesting.',
      howToFix: 'Store secrets in environment variables or AWS Secrets Manager.',
      nonCompliant: 'AWS_SECRET_KEY = "AKIAIOSFODNN7EXAMPLE"',
      compliant: 'AWS_SECRET_KEY = os.environ.get("AWS_SECRET_ACCESS_KEY")'
    }
  },
  {
    id: 'ISSUE-1005',
    key: 'AWx908238-TS-DUPLICATE',
    ruleKey: 'typescript:S1186',
    ruleName: 'Empty functions should be removed or commented',
    severity: 'MINOR',
    type: 'CODE_SMELL',
    status: 'OPEN',
    message: 'Empty arrow function handler without explanatory comment.',
    projectKey: 'com.frontend:storefront-nextjs',
    projectName: 'storefront-ecommerce-ui',
    component: 'src/components/cart/CartDrawer.tsx',
    line: 82,
    effortMinutes: 5,
    author: 'm.kahn@frontend.com',
    creationDate: '2026-07-21T14:05:00Z',
    updateDate: '2026-07-21T14:05:00Z',
    tags: ['code-smell', 'maintainability'],
    codeSnippet: [
      { line: 80, code: '  return (' },
      { line: 81, code: '    <button' },
      { line: 82, code: '      onClick={() => {}}', issueId: 'ISSUE-1005', issueSeverity: 'MINOR', issueMessage: 'Empty function body' },
      { line: 83, code: '      className="btn-checkout"' },
      { line: 84, code: '    >' },
    ],
  }
];

export const MOCK_QUALITY_GATES: QualityGate[] = [
  {
    id: 'gate-sonar-way',
    name: 'Sonar way',
    isDefault: true,
    conditions: [
      { id: 'c1', metric: 'new_coverage', metricName: 'Coverage on New Code', op: 'LT', errorThreshold: '80.0', period: 'NEW_CODE' },
      { id: 'c2', metric: 'new_duplicated_lines_density', metricName: 'Duplicated Lines (%) on New Code', op: 'GT', errorThreshold: '3.0', period: 'NEW_CODE' },
      { id: 'c3', metric: 'new_maintainability_rating', metricName: 'Maintainability Rating on New Code', op: 'GT', errorThreshold: '1', period: 'NEW_CODE' },
      { id: 'c4', metric: 'new_reliability_rating', metricName: 'Reliability Rating on New Code', op: 'GT', errorThreshold: '1', period: 'NEW_CODE' },
      { id: 'c5', metric: 'new_security_rating', metricName: 'Security Rating on New Code', op: 'GT', errorThreshold: '1', period: 'NEW_CODE' },
      { id: 'c6', metric: 'new_security_hotspots_reviewed', metricName: 'Security Hotspots Reviewed on New Code', op: 'LT', errorThreshold: '100.0', period: 'NEW_CODE' },
    ],
  },
  {
    id: 'gate-strict-financial',
    name: 'Strict Financial PCI Gate',
    isDefault: false,
    conditions: [
      { id: 'fc1', metric: 'coverage', metricName: 'Overall Coverage', op: 'LT', errorThreshold: '85.0', period: 'OVERALL' },
      { id: 'fc2', metric: 'bugs', metricName: 'Open Bugs', op: 'GT', errorThreshold: '0', period: 'OVERALL' },
      { id: 'fc3', metric: 'vulnerabilities', metricName: 'Open Security Vulnerabilities', op: 'GT', errorThreshold: '0', period: 'OVERALL' },
      { id: 'fc4', metric: 'sqale_rating', metricName: 'Overall Maintainability Rating', op: 'GT', errorThreshold: '1', period: 'OVERALL' },
    ],
  },
];

export const MOCK_QUALITY_PROFILES: QualityProfile[] = [
  { key: 'qp-java-sonar-way', name: 'Sonar way', language: 'java', languageName: 'Java', isDefault: true, activeRuleCount: 612, deprecatedRuleCount: 4, updatedAt: '2026-06-15' },
  { key: 'qp-ts-sonar-way', name: 'Sonar way Recommended', language: 'typescript', languageName: 'TypeScript', isDefault: true, activeRuleCount: 385, deprecatedRuleCount: 1, updatedAt: '2026-07-01' },
  { key: 'qp-go-sonar-way', name: 'Sonar way', language: 'go', languageName: 'Go', isDefault: true, activeRuleCount: 210, deprecatedRuleCount: 0, updatedAt: '2026-05-10' },
  { key: 'qp-py-sonar-way', name: 'Sonar way', language: 'python', languageName: 'Python', isDefault: true, activeRuleCount: 320, deprecatedRuleCount: 2, updatedAt: '2026-06-20' },
];

export const MOCK_RULES: RuleDefinition[] = [
  {
    key: 'java:S2077',
    name: 'SQL queries should be constructed using parameterized queries',
    lang: 'Java',
    type: 'VULNERABILITY',
    severity: 'CRITICAL',
    status: 'READY',
    sysTags: ['sql', 'cwe-89', 'owasp-a1', 'security'],
    htmlDesc: '<p>Constructing SQL queries dynamically by concatenating user inputs allows attackers to alter query execution flow.</p>',
    remediationEffort: '30min',
  },
  {
    key: 'typescript:S2259',
    name: 'Null pointers should not be dereferenced',
    lang: 'TypeScript',
    type: 'BUG',
    severity: 'MAJOR',
    status: 'READY',
    sysTags: ['cwe-476', 'type-safety', 'bug'],
    htmlDesc: '<p>Attempting to read properties or call methods on null or undefined values throws runtime TypeErrors.</p>',
    remediationEffort: '15min',
  },
  {
    key: 'go:S2699',
    name: 'Goroutines should synchronize access to shared memory',
    lang: 'Go',
    type: 'BUG',
    severity: 'BLOCKER',
    status: 'READY',
    sysTags: ['concurrency', 'race-condition'],
    htmlDesc: '<p>Concurrent mutations to non-synchronized Go maps cause fatal runtime crashes.</p>',
    remediationEffort: '45min',
  },
  {
    key: 'python:S1812',
    name: 'Hardcoded credentials should not be stored in source code',
    lang: 'Python',
    type: 'VULNERABILITY',
    severity: 'CRITICAL',
    status: 'READY',
    sysTags: ['cwe-798', 'security', 'owasp-a7'],
    htmlDesc: '<p>Hardcoded credentials, passwords, or secret keys in source code leak authorization access to unauthorized parties.</p>',
    remediationEffort: '10min',
  },
];

export const MOCK_METRICS_LIST: MetricDefinition[] = [
  { key: 'bugs', name: 'Bugs', category: 'RELIABILITY', type: 'INT', description: 'Total count of reliability bugs' },
  { key: 'reliability_rating', name: 'Reliability Rating', category: 'RELIABILITY', type: 'RATING', description: 'A-E Rating based on worst bug severity' },
  { key: 'vulnerabilities', name: 'Vulnerabilities', category: 'SECURITY', type: 'INT', description: 'Total count of security vulnerabilities' },
  { key: 'security_rating', name: 'Security Rating', category: 'SECURITY', type: 'RATING', description: 'A-E Rating based on worst vulnerability severity' },
  { key: 'code_smells', name: 'Code Smells', category: 'MAINTAINABILITY', type: 'INT', description: 'Maintainability issues needing refactoring' },
  { key: 'sqale_index', name: 'Technical Debt', category: 'MAINTAINABILITY', type: 'WORK_DUR', description: 'Effort to fix all code smells' },
  { key: 'coverage', name: 'Coverage', category: 'COVERAGE', type: 'PERCENT', description: 'Percentage of covered lines by unit tests' },
  { key: 'duplicated_lines_density', name: 'Duplications', category: 'DUPLICATIONS', type: 'PERCENT', description: 'Percentage of duplicated code blocks' },
  { key: 'ncloc', name: 'Lines of Code', category: 'SIZE', type: 'INT', description: 'Non-commented lines of code' },
];

export const MOCK_FILE_TREE: FileNode = {
  path: 'src',
  name: 'src',
  type: 'dir',
  children: [
    {
      path: 'src/main',
      name: 'main',
      type: 'dir',
      children: [
        {
          path: 'src/main/java',
          name: 'java',
          type: 'dir',
          children: [
            {
              path: 'src/main/java/com/acme/payment/repository/PaymentDAO.java',
              name: 'PaymentDAO.java',
              type: 'file',
              ncloc: 142,
              bugs: 0,
              vulnerabilities: 1,
              codeSmells: 3,
              coverage: 72.4,
              duplications: 0.0,
              content: [
                { line: 1, code: 'package com.acme.payment.repository;' },
                { line: 2, code: '' },
                { line: 3, code: 'import java.sql.Connection;' },
                { line: 4, code: 'import java.sql.ResultSet;' },
                { line: 5, code: 'import java.sql.Statement;' },
                { line: 6, code: 'import java.util.List;' },
                { line: 7, code: 'import java.util.ArrayList;' },
                { line: 8, code: '' },
                { line: 9, code: 'public class PaymentDAO {' },
                { line: 10, code: '    private final DatabasePool dbPool;' },
                { line: 11, code: '' },
                { line: 12, code: '    public PaymentDAO(DatabasePool dbPool) {' },
                { line: 13, code: '        this.dbPool = dbPool;' },
                { line: 14, code: '    }' },
                { line: 15, code: '' },
                { line: 38, code: '    public List<Transaction> findByAccountAndType(String accountId, String type) {' },
                { line: 39, code: '        Connection conn = dbPool.getConnection();', isCovered: true },
                { line: 40, code: '        Statement stmt = conn.createStatement();', isCovered: true },
                { line: 41, code: '        // Unsanitized raw dynamic query assembly', isCovered: true },
                { line: 42, code: '        String sql = "SELECT * FROM transactions WHERE account_id = \'" + accountId + "\' AND type = \'" + type + "\'";', isUncovered: true, issueId: 'ISSUE-1001', issueSeverity: 'CRITICAL', issueMessage: 'SQL Injection Risk: accountId concatenated directly' },
                { line: 43, code: '        ResultSet rs = stmt.executeQuery(sql);', isUncovered: true },
                { line: 44, code: '        return parseTransactions(rs);', isCovered: true },
                { line: 45, code: '    }' },
                { line: 46, code: '}' },
              ]
            },
            {
              path: 'src/main/java/com/acme/payment/service/PaymentService.java',
              name: 'PaymentService.java',
              type: 'file',
              ncloc: 280,
              bugs: 1,
              vulnerabilities: 0,
              codeSmells: 5,
              coverage: 88.0,
              duplications: 1.2
            }
          ]
        }
      ]
    },
    {
      path: 'src/features',
      name: 'features',
      type: 'dir',
      children: [
        {
          path: 'src/features/auth/useSession.ts',
          name: 'useSession.ts',
          type: 'file',
          ncloc: 95,
          bugs: 1,
          vulnerabilities: 0,
          codeSmells: 1,
          coverage: 92.0,
          duplications: 0.0,
          content: [
            { line: 20, code: 'import { useState, useEffect } from "react";' },
            { line: 21, code: 'import { SessionResponse } from "./types";' },
            { line: 22, code: '' },
            { line: 25, code: 'export function getUserDisplayName(sessionResponse: SessionResponse | null): string {' },
            { line: 26, code: '  const user = sessionResponse.data?.user;', isCovered: true },
            { line: 27, code: '  // Missing check for user existence before accessing profile property', isCovered: true },
            { line: 28, code: '  return user.profile.firstName + " " + user.profile.lastName;', isUncovered: true, issueId: 'ISSUE-1002', issueSeverity: 'MAJOR', issueMessage: 'Object is possibly "undefined"' },
            { line: 29, code: '}' },
          ]
        }
      ]
    }
  ]
};

export const MOCK_SYSTEM_INFO: SystemInfo = {
  version: '10.6.0.92143 Enterprise Edition',
  serverUptime: '14 days 8 hours',
  dbStatus: 'CONNECTED',
  searchEngineStatus: 'GREEN',
  diskSpaceFreeGb: 142.8,
  activeBackgroundTasks: 0,
  totalProjectsCount: 5,
  totalIssuesCount: 109,
};
