#!/usr/bin/env bash
# Renders the Homebrew formula for the current release, reading the real
# SHA-256 of each published artifact from the build jobs' `.sha256` files.
#
#   VERSION=0.1.1 render-formula.sh <artifacts-dir> > vord.rb
#
# A missing checksum is a hard error: a formula that ships without one, or
# with a stale one, installs an unverified binary on every user's machine.

set -euo pipefail

dir="${1:?usage: render-formula.sh <artifacts-dir>}"
version="${VERSION:?VERSION is required}"

sum_for() {
  local asset="$1"
  local file
  file="$(find "$dir" -name "${asset}.sha256" -print -quit)"
  [ -n "$file" ] || { echo "missing checksum for $asset" >&2; exit 1; }
  awk '{print $1}' "$file"
}

mac_arm="$(sum_for "vord-aarch64-apple-darwin")"
mac_x86="$(sum_for "vord-x86_64-apple-darwin")"
linux_arm="$(sum_for "vord-aarch64-unknown-linux-musl")"
linux_x86="$(sum_for "vord-x86_64-unknown-linux-musl")"

base="https://github.com/pmaojo/vord/releases/download/v${version}"

cat <<EOF
# typed: false
# frozen_string_literal: true

# Generated by packaging/homebrew/render-formula.sh — do not edit by hand.
class Vord < Formula
  desc "Ultraperformant static analysis with an agent guardrail that judges writes before they land"
  homepage "https://github.com/pmaojo/vord"
  version "${version}"
  license "MIT"

  on_macos do
    on_arm do
      url "${base}/vord-aarch64-apple-darwin"
      sha256 "${mac_arm}"
    end
    on_intel do
      url "${base}/vord-x86_64-apple-darwin"
      sha256 "${mac_x86}"
    end
  end

  on_linux do
    on_arm do
      url "${base}/vord-aarch64-unknown-linux-musl"
      sha256 "${linux_arm}"
    end
    on_intel do
      url "${base}/vord-x86_64-unknown-linux-musl"
      sha256 "${linux_x86}"
    end
  end

  def install
    bin.install Dir["vord-*"].first => "vord"
  end

  test do
    assert_match "vord", shell_output("#{bin}/vord --version")
  end
end
EOF
