[package]
name = "yunq-parser-dockerfile"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
yunq-ast = { workspace = true }
yunq-rules-engine = { workspace = true }
tree-sitter = { workspace = true }
tree-sitter-dockerfile = "0.2.0"
