[package]
name = "yunq-taint"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
yunq-ast = { workspace = true }
thiserror = { workspace = true }

[dev-dependencies]
yunq-rules-engine = { workspace = true }
yunq-parser-typescript = { workspace = true }
