[package]
name = "yunq-taint"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true
description = "Intra-file and cross-file inter-procedural taint analysis for yunq"
repository.workspace = true
homepage.workspace = true
keywords.workspace = true
categories.workspace = true

[dependencies]
yunq-ast = { workspace = true }
thiserror = { workspace = true }

[dev-dependencies]
yunq-rules-engine = { workspace = true }
yunq-parser-typescript = { workspace = true }
