[package]
name = "yunq-rules-python"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true
description = "Python-specific ruleset for the yunq analysis engine"
repository.workspace = true
homepage.workspace = true
keywords.workspace = true
categories.workspace = true

[dependencies]
yunq-ast = { workspace = true }
yunq-rules-engine = { workspace = true }
littrs-ruff-python-parser = "0.6.2"

[dev-dependencies]
yunq-parser-python = { workspace = true }
