[package]
name = "yunq-treesitter-tokens"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
yunq-cpd = { path = "../../core/duplication" }
tree-sitter = { workspace = true }

[dev-dependencies]
tree-sitter-python = { workspace = true }
